In [2]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Priya", "Anu"],
    "Age": [21, 22, 20, 23],
    "Department": ["AI&DS", "CSE", "ECE", "IT"],
    "CGPA": [8.2, 7.9, 8.8, 9.1]
}

df = pd.DataFrame(data)

print(df)

     Name  Age Department  CGPA
0  Harish   21      AI&DS   8.2
1   Rahul   22        CSE   7.9
2   Priya   20        ECE   8.8
3     Anu   23         IT   9.1

In [3]:
df.head()

     Name  Age Department  CGPA
0  Harish   21      AI&DS   8.2
1   Rahul   22        CSE   7.9
2   Priya   20        ECE   8.8
3     Anu   23         IT   9.1

In [4]:
df.tail()

     Name  Age Department  CGPA
0  Harish   21      AI&DS   8.2
1   Rahul   22        CSE   7.9
2   Priya   20        ECE   8.8
3     Anu   23         IT   9.1

In [5]:
df.shape

(4, 4)

In [6]:
df.columns

Index(['Name', 'Age', 'Department', 'CGPA'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Age         4 non-null      int64
 2   Department  4 non-null      object
 3   CGPA        4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [8]:
df.describe()

             Age      CGPA
count   4.000000  4.000000
mean   21.500000  8.500000
std     1.290994  0.547723
min    20.000000  7.900000
25%    20.750000  8.125000
50%    21.500000  8.500000
75%    22.250000  8.875000
max    23.000000  9.100000

In [9]:
new_student = {
    "Name": "Kiran",
    "Age": 22,
    "Department": "CSE",
    "CGPA": 8.7
}

df.loc[len(df)] = new_student

print(df)

     Name  Age Department  CGPA
0  Harish   21      AI&DS   8.2
1   Rahul   22        CSE   7.9
2   Priya   20        ECE   8.8
3     Anu   23         IT   9.1
4   Kiran   22        CSE   8.7

In [10]:
df["City"] = ["Trichy", "Chennai", "Madurai", "Coimbatore", "Salem"]

print(df)

     Name  Age Department  CGPA        City
0  Harish   21      AI&DS   8.2      Trichy
1   Rahul   22        CSE   7.9     Chennai
2   Priya   20        ECE   8.8     Madurai
3     Anu   23         IT   9.1  Coimbatore
4   Kiran   22        CSE   8.7       Salem

In [11]:
print(df["Name"])

0    Harish
1     Rahul
2     Priya
3       Anu
4     Kiran
Name: Name, dtype: object

In [12]:
print(df[df["CGPA"] > 8.5])

    Name  Age Department  CGPA        City
2  Priya   20        ECE   8.8     Madurai
3    Anu   23         IT   9.1  Coimbatore
4  Kiran   22        CSE   8.7       Salem

In [13]:
df.loc[0]

Name          Harish
Age               21
Department     AI&DS
CGPA             8.2
City          Trichy
Name: 0, dtype: object